# Generated by Django 2.1 on 2018-08-27 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Deployment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deployment_name', models.CharField(max_length=100)),
                ('namespace', models.CharField(max_length=20)),
                ('image_version', models.CharField(max_length=20)),
            ],
        ),
    ]
