# Generated by Django 2.1 on 2018-08-27 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deployment', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='deployment',
            old_name='image_version',
            new_name='version',
        ),
        migrations.AddField(
            model_name='deployment',
            name='available',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='deployment',
            name='desired',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='deployment',
            name='unavailable',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='deployment',
            name='updated',
            field=models.IntegerField(default=0),
        ),
    ]
