# Generated by Django 2.1 on 2018-08-28 02:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('deployment', '0005_auto_20180827_2205'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Deployment',
        ),
    ]
