# Generated by Django 2.1 on 2018-08-28 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deployment', '0007_deployment'),
    ]

    operations = [
        migrations.AddField(
            model_name='deployment',
            name='available',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='deployment',
            name='desired',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='deployment',
            name='svc_version',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='deployment',
            name='unavailable',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='deployment',
            name='updated',
            field=models.IntegerField(null=True),
        ),
    ]
